const productos = [{
    id: 1,
    foto: '../img/auriculares-logitech-G935.jpeg',
    nombre: "auriculares logitech G935",
    precio: 60000,
    categoria: "accesoriospc",
    cantidad: 1,
},
{
    id: 2,
    foto: '../img/auriculares-JBL.webp',
    nombre: "auriculares JBL",
    precio: 10000,
    categoria: "accesoriospc",
    cantidad: 1,
},
{
    id: 3,
    foto: "../img/auriculares-hp.jpg",
    nombre: "auriculares hp",
    precio: 40000,
    categoria: "accesoriospc",
    cantidad: 1,
},
{
    id: 4,
    foto: '../img/pc-ar-core-i5.jpg',
    nombre: "pc ar completa core i5",
    precio: 130000,
    categoria: "computadoras",
    cantidad: 1,
},
{
    id: 5,
    foto: '../img/pc-amd-ryzen5.jpg',
    nombre: "pc gamer amd ryzen 5",
    precio: 250000,
    categoria: "computadoras",
    cantidad: 1,
},
{
    id: 6,
    foto: "../img/PC-GAMER-INTEL-KAIROS-COREI3.png",
    nombre: "PC GAMER INTEL KAIROS CORE I3",
    precio: 373000,
    categoria: "computadoras",
    cantidad: 1,
},
{
    id: 7,
    foto: '../img/NOTEBOOK-HP245.webp',
    nombre: "NOTEBOOK HP 245",
    precio: 180000,
    categoria: "notebook",
    cantidad: 1,
},
{
    id: 8,
    foto: '../img/NOTEBOOK-ACER-ASPIRE5.webp',
    nombre: "NOTEBOOK ACER ASPIRE 5",
    precio: 225000,
    categoria: "notebook",
    cantidad: 1,
},
{
    id: 9,
    foto: '../img/NOTEBOOK-LENOVOV15.webp',
    nombre: "NOTEBOOK LENOVO V15",
    precio: 188000,
    categoria: "notebook",
    cantidad: 1,
},
];

